micronaut:
  application:
    name: rest
  caches:
    my-cache:
      maximumSize: 20
  security:
    authentication: cookie
    oauth2:
      clients:
        default:
          client-id: ${OAUTH_CLIENT_ID}
          client-secret: ${OAUTH_CLIENT_SECRET}
datasources:
  default:
    url: jdbc:mysql://localhost:3306/db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
hystrix.stream.enabled: false
elasticsearch.httpHosts: '"http://localhost:9200,http://127.0.0.2:9200"'
